---
COMMON_LOCAL_USER_HOME: "/home/{{ ansible_facts.env.SUDO_USER }}"
COMMON_LOCAL_PROJECTS_DIR: "{{ COMMON_LOCAL_USER_HOME }}/Projects/MINE"
COMMON_INSTALL_DIR: "/opt"
COMMON_EXEC_DIR: "/usr/local/bin"
